### ISSUE TITLE
Horizontal Overflow

### ISSUE THREAD

**Issue by ugurakcora** [GoktugYalcin/next-portfolio-sample#1]
If you remove the "w-screen" class you added to the body to prevent horizontal overflow, there will be no problem.

Before: ![image](https://github.com/GoktugYalcin/next-portfolio-sample/assets/45590367/1005a327-b8ff-4817-b674-7a120cba634a)

After: ![image](https://github.com/GoktugYalcin/next-portfolio-sample/assets/45590367/2224482a-11d7-401d-9bfb-6d069bbf097e)

**Comment by GoktugYalcin** [comment]
I never tested it on Windows, saw when you mentioned it now. Thanks a lot, I will reproduce it🫡

**Comment by GoktugYalcin** [comment]
@ugurakcora its done on: https://github.com/GoktugYalcin/next-portfolio-sample/commit/ee93b24948a7f4171f859aed9c0d2edbb2e33779
